### PR TITLE
A bunch of new features

### PR DESCRIPTION
**Pull request by cosban**
This pull request adds invisibility mode, opt-in topic sharing, chat with friends, chat with people in the same topic.

### CODE REVIEW

**Comment by cosban** [comment]
oh, let me see what the conflicts are I guess.

**Comment by william-mcmillian** [comment]
I think you should fix up the angular before I pull this. Don't do element manipulation inside factories. You shouldn't need any element manipulation at all actually, just have an array of chat messages and display them via angular templating. 

Angular projects with this kind of jquery scattered throughout become maintenance nightmares.

**Comment by cosban** [comment]
Fair. I'll get on doing that.

**Comment by cosban** [comment]
Do you care about the chat windows overlapping? If so, do you know of a better way to prevent that without element manipulation?

Otherwise this should be ready.

**Comment by william-mcmillian** [comment]
nah, not really - probably display:flex is the easy answer. i'll take a
looksie and pull it

**Comment by cosban** [comment]
flex doesn't seem to work. I have it just programmatically set the horizontal position for now.

**Pull request merged**
